### ISSUE TITLE
Suggestion : DungeonTactics support

### ISSUE THREAD

**Issue by jinkhya** [jredfox/dungeontweeks#14]
Hello ! 
Would it be possible to add support for DungeonTactics? :)
Jin

**Comment by jredfox** [comment]
you could ask the mod owner to add support. Tell him to call DungeonMobs.fireDungeonEvent() with the parameters then it should be compatible. You would also need to define it in the main config.

The reason why it's incompatible with everything is because each dungeon defines it's own list or uses the default vanilla dungeon not their own. I changed that with this mod so manual support is required on their side.

**Comment by jredfox** [comment]
Not really an issue like to keep this open for bugs but, will answer your questions here. there isn't really anything I could do on my side to add comparability besides replace another mods classes.

**Comment by jinkhya** [comment]
Alrighty thanks for the very quick answer, i linked this thread to the request on dungeontactics issues'page. I'll come back to you as you as i know more.
