### ISSUE TITLE
Wind sound on main menu when both Dungeontweaks and MowziesMobs are installed

### ISSUE THREAD

**Issue by jinkhya** [jredfox/dungeontweeks#16]
Version: 1.2.5.2
Issue: Wind sound on main menu

Steps to reproduce:
mods to install : 
- Forge 2768
- DungeonTweaks-1.2.5.2.jar
- EvilNotchLib-1.2.3-SNAPSHOt-78.jar
- mowziesmobs-1.4.2.jar
- llibrary-1.7.15-1.12.2.jar
Nothing changed in default configs.
Launch the pack, at around 5/7 you'll get a wind sound that stays even on main menu once the pack is fully loaded and I have no idea why. I tested forge + mowziesmobs and forge + dungeontweaks and I don't get that wind sound separately. So it seems to be a compatibility issue between those two mods.

Here's my debug.log : 
https://pastebin.com/fEeCvjpG

Thanks in advance.

**Comment by jredfox** [comment]
I am sorry but, dungeon tweaks has no such code to produce such a sound

**Comment by jinkhya** [comment]
then it must be on Mowziesmobs side?
I don't really understand why the issue only happens if your mod AND Mowzies is present though.

**Comment by jredfox** [comment]
there is code to replace the main gui with menu lib but, I have no such music on my side.

Either way this is the wrong place to put the issue evil notch lib is the one you should place it upon

**Comment by jinkhya** [comment]
did you try reproducing the issue? Or would that issue only be on my pc, I pinned  wich mod was giving me the sound, and then created a modpack on twitch with fresh installs without touching anything.

**Comment by jredfox** [comment]
issue isn't caused by dungeon tweaks side it's either evil notch lib or mowies mobs

**Comment by jredfox** [comment]
I don't see any evidence of this being on evil notch's lib side either. Please report this to mowie's mobs

**Comment by jinkhya** [comment]
I did already ;) thanks for your fast answer, I'll wait on Mowzie's dev answer

**Comment by jredfox** [comment]
Actually this is weird the sound doesn't play unless dungeon tweaks is installed. This doesn't make any sense I have no code on my side that has asm with dungeon tweaks.

**Comment by jredfox** [comment]
Does the issue happen with main menu mobs as well?

**Comment by jinkhya** [comment]
It is weird huh :)

**Comment by jredfox** [comment]
Silkspawners and dungeon tweaks work similar to main menu mobs so it could be causing issues.

**Comment by jinkhya** [comment]
main menu mobs?

**Comment by jredfox** [comment]
I create entities in post init to see if they will break later or not since so many mods had broken mobs and blaimed my mods for their broken entities. Then if no exceptions occur I add the resource location to a list. 

https://minecraft.curseforge.com/projects/menumobs
menu mobs doesn't cause the bug yet they use a fake world just as I do. 

Add this to your report. "I create entities in post init to see if they will break with silkspawners or dungeon tweaks later. I think your entities are doing something wrong by playing a sound on creation. There is no tick on the world"
https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/evilnotch/lib/minecraft/content/world/FakeWorld.java

**Comment by jredfox** [comment]
I still think it's their side trying one more thing if not it's their side for doing something wrong

**Comment by jinkhya** [comment]
Mowzie's dev should see it here, I linked this thread directly. Also I forgot to mention but to turn down that wind, you need to use "Friendly Creatures" oddly enough.

**Comment by jhth13rteen** [comment]
I am also having this problem and its really friggin annoying. I have traced the exact sound to Mowzie's Mob in the following directory of the .jar file: 
mowziesmobs-1.5.4.jar\assets\mowziesmobs\sounds\entity\frostmaw

Its the following file: icebreath.ogg

For some weird reason this and/or evilnotch is causing this sound to fire on init 5/7 progress on forge loader bar as stated above.

Anyone know exactly what the heck "use Friendly Creatures" means from jinkhya's post above? Its so cryptic i have no idea what to do with that...

Edit: To hell with it. I just deleted Mowzie's Mobs. Screw it.

**Comment by jredfox** [comment]
the issue was they were playing mob sounds wrongly. my system was suppose to stop it but, never got around to completly fixing it.

these are legacy versions I will be working on a mod loader soon to replace forge then update mods to my system and if something breaks it will be the mods fault not mine even though it was clearly their code to begin with
