### ISSUE TITLE
Crashing before load

### ISSUE THREAD

**Issue by jprocket45** [jredfox/dungeontweeks#9]
Version:1.2.4.8
Issue: it crashes when i hit play
Steps to reproduce::loads by itself added Silk Spawners when i hit play it says Game Crash An unexpected issue occured and the game has crashes We're sorry for the inconvenience....

CrashReport/Log: I have a log but can't post it public I can send it to you another way im willing to if not well i can't post the log with my real name in the crash report logs this time, though it should be easy to duplicate this crash since the game does not start :) lol 
ModPack/ModList: pastebin.com/example_file.txt   

Dungeon Tweaks,EvilNotch Lib, Silk Spawners Forge Edition   Forge 2759

**Comment by jredfox** [comment]
remove your name from the crash log or simply join my discord:
https://discord.gg/Y8sHf52

I can't fix anything unless I get the report

**Comment by jprocket45** [comment]
this is not the mod i reported on im assuming this maybe a new issues due to its nothing to do with server side, I will get a log to you soon then.

**Comment by jredfox** [comment]
ok also provide evil notch lib and other mod versions.

**Comment by jprocket45** [comment]
https://pastebin.com/SiYHH8nP

Dungeon Tweaks 1.2.4.8
EvilNotch Lib 1.2.02
SilkSpawners Forge Edition 1.8
Forge 2759

**Comment by jredfox** [comment]
there is your problem right there evil notch lib needs to be latest 99% of the time. The only reason why that was a "release" version was because there was very little code added to the lib at the time so it was bug free. Now there is about 200 classes. I will mark the lib as a release when I am done getting it stable and fully functioning again.

" at com.EvilNotch.silkspawners.asm.SilkTransformer.<clinit>" should have reported that to silkspawners not dungeon tweaks lol

if error still persists comment
